# yaml-language-server: $schema=https://raw.githubusercontent.com/chainguard-dev/melange/main/pkg/config/schema.json

package:
  name: bun-application
  version: 0.1.0
  description: A bun application
  target-architecture: [aarch64]
  epoch: 0
  copyright:
    - license: MIT

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
      - ./melange.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - ca-certificates-bundle
      - busybox
      - bun

pipeline:
  - name: Build
    runs: |
      set -eou pipefail
      INSTALLDIR="${{targets.destdir}}/usr/bin"
      mkdir -p "${INSTALLDIR}"
      bun install --frozen-lockfile
      bun build src/index.ts --compile --outfile "${INSTALLDIR}/bun-application"
      chmod +x "${INSTALLDIR}/bun-application"
